"""
389. Find the Difference
Easy
Topics
premium lock icon
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """

        for letter in s:
            t = str(t).replace(letter, "", 1)
        return t


sol = Solution()
print(sol.findTheDifference("abcd", "abcde"))
print(sol.findTheDifference("", "y"))
print(sol.findTheDifference("a", "aa"))
print(sol.findTheDifference("b", "aa"))
